workflows:
  release:
    name: Release (Tag -> Store)
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "IOSAPP_TEAM_E" 
    environment:
      groups:
        - ios_credentials
      vars:
        FLUTTER_CHANNEL: "stable"
        APP_ENV: "prod"
        DART_DEFINES: "ENV=prod"
        ANDROID_FLAVOR: "prod"
      # --- ここを最新にアップデート ---
      flutter: "3.38.9"   # エラーメッセージの推奨バージョンに合わせる
      xcode: "17.0"       # Flutter 3.38以降は最新のXcodeを推奨
      cocoapods: "1.16.2" # 最新のCocoaPods
      # ----------------------------
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Set up GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist
      - name: Flutter deps
        script: |
          # プロジェクトのルートに移動してから実行
          flutter pub get
          # Podfileがないという警告への対策: iosフォルダが存在するか確認して実行
          if [ -d "ios" ]; then
            cd ios && pod install --repo-update && cd ..
          fi
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      #- name: Tests
      #  script: |
      #    flutter test
      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES} \
      #      --export-options-plist=ios/exportOptions.plist
      - name: Upload dSYM to Firebase Crashlytics
        script: |
          # アーカイブが存在する場合のみdSYMをアップロード
          if [ -d "build/ios/archive" ]; then
            find build/ios/archive -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"
          fi
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      slack:
        channel: "#ci-notify"
        notify:
          success: true
          failure: true