workflows:
  release:
    name: Release (Tag -> Store)
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "IOSAPP_TEAM_E" 
    environment:
      groups:
        - ios_credentials # ここに GOOGLE_SERVICE_INFO_IOS, FIREBASE_APP_ID_IOS 等を設定
      vars:
        FLUTTER_CHANNEL: "stable"
        APP_ENV: "prod"
        DART_DEFINES: "ENV=prod"
        ANDROID_FLAVOR: "prod"
      flutter: "3.38.9"
      xcode: "17.0"
      cocoapods: "1.16.2"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Force Automatic Signing (Windows Fix)
        script: |
          # ProvisioningStyle を Manual から Automatic に変換
          sed 's/ProvisioningStyle = Manual/ProvisioningStyle = Automatic/g' ios/Runner.xcodeproj/project.pbxproj > project.pbxproj.tmp && mv project.pbxproj.tmp ios/Runner.xcodeproj/project.pbxproj
          
          # CODE_SIGN_STYLE を Manual から Automatic に変換
          sed 's/CODE_SIGN_STYLE = Manual/CODE_SIGN_STYLE = Automatic/g' ios/Runner.xcodeproj/project.pbxproj > project.pbxproj.tmp && mv project.pbxproj.tmp ios/Runner.xcodeproj/project.pbxproj
          
          # 変換が正しく行われたか確認するためのログ（デバッグ用）
          grep "ProvisioningStyle" ios/Runner.xcodeproj/project.pbxproj
          grep "CODE_SIGN_STYLE" ios/Runner.xcodeproj/project.pbxproj
      - name: Set up GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist
      - name: Flutter deps
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
      - name: Set up code signing
        script: |
          # CodemagicがAPIキーからプロファイルを生成・取得する
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          # 1. 署名なしでアーカイブを作成
          # ここで明示的に CODE_SIGNING_ALLOWED=NO を渡して Xcode の署名チェックを回避します
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES} \
            --no-codesign

          # 2. アーカイブから IPA を作成する際、プロジェクトの設定を「引数」で上書きします
          # CODE_SIGN_STYLE="Automatic" を渡すことで、Manual設定を無効化します
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-directory build/ios/archive \
            --export-flags "CODE_SIGN_STYLE=Automatic"
      - name: Upload dSYM to Firebase Crashlytics
        script: |
          # 確実にdSYMを見つけるためのパス指定
          find build/ios/archive -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      slack:
        channel: "#ci-notify"
        notify:
          success: true
          failure: true