workflows:
  release:
    name: Release (Tag -> Store)
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "IOSAPP_TEAM_E" 
    environment:
      groups:
        - ios_credentials
      vars:
        FLUTTER_CHANNEL: "stable"
        APP_ENV: "prod"
        DART_DEFINES: "ENV=prod"
        ANDROID_FLAVOR: "prod"
      flutter: "3.38.9"   # エラーメッセージの推奨バージョンに合わせる
      xcode: "17.0"       # Flutter 3.38以降は最新のXcodeを推奨
      cocoapods: "1.16.2" # 最新のCocoaPods
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Set up GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist
      - name: Flutter deps
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          # 1. まず署名なしでアーカイブを作成（これは既に成功しています）
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES} \
            --no-codesign

          # 2. Codemagicのツールを使って、IPA作成と署名を一気に行う
          # Web画面で設定した App Store 配信用のプロファイルが自動注入されます
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
      - name: Upload dSYM to Firebase Crashlytics
        script: |
          # より確実にファイルを拾うため find の検索範囲を広げています
          find build/ios -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      slack:
        channel: "#ci-notify"
        notify:
          success: true
          failure: true