workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60 # 無駄な消費を防ぐため制限
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "IOSAPP_TEAM_E" 
    environment:
      groups:
        - ios_credentials
      vars:
        FLUTTER_CHANNEL: "stable"
        DART_DEFINES: "ENV=prod"
      flutter: "3.38.9"
      xcode: "17.0"
      cocoapods: "1.16.2"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Force Automatic Signing (Fix for Windows users)
        script: |
          # プロジェクトファイルを直接書き換え、Xcodeの手動署名エラーを物理的に消去
          find . -name "project.pbxproj" -exec sed -i '' 's/Manual/Automatic/g' {} +
          find . -name "CODE_SIGN_STYLE = Manual" -exec sed -i '' 's/CODE_SIGN_STYLE = Manual/CODE_SIGN_STYLE = Automatic/g' {} +
          
      - name: Set up GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist

      - name: Flutter dependencies & Caching
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Set up code signing
        script: |
          # APIキー（Integration）から配信用の証明書とプロファイルを自動生成/取得
          xcode-project use-profiles

      - name: Build iOS IPA (Fast Mode)
        script: |
          # 署名なしアーカイブ作成（ビルド時間の節約）
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES} \
            --no-codesign

          # 作成されたアーカイブを強制的にAutomatic SigningでIPA化
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-directory build/ios/archive \
            --export-flags "CODE_SIGN_STYLE=Automatic"

      - name: Upload dSYM to Firebase
        script: |
          # クラッシュ解析用のデバッグファイルをFirebaseへ送信
          find build/ios/archive -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true # 自動でTestFlightへアップロード