workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "IOSAPP_TEAM_E" 
    environment:
      groups:
        - ios_credentials
      vars:
        FLUTTER_CHANNEL: "stable"
        DART_DEFINES: "ENV=prod"
      flutter: "3.24.5"
      xcode: "16.1"
      cocoapods: default
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Force Automatic Signing & Build Fix
        script: |
          # 1. プロジェクトファイルを物理的に書き換え（Manualを徹底排除）
          find . -name "project.pbxproj" -exec sed -i '' 's/Manual/Automatic/g' {} +
          find . -name "project.pbxproj" -exec sed -i '' 's/ProvisioningStyle = Manual/ProvisioningStyle = Automatic/g' {} +
          
          # 2. GoogleService-Info.plistの配置
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist

      - name: Flutter deps & Pods
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Set up code signing
        script: |
          # Codemagicに証明書とプロファイルを準備させ、パスを取得する
          xcode-project use-profiles

      - name: Build and Sign IPA (Final Strike)
        script: |
          # ビルド番号を100底上げし、かつCodemagicが生成した設定(ExportOptions)を使って一本でビルド
          # これにより Status 65 エラーを回避し、ビルド時間を最短にします
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=$((BUILD_NUMBER + 100)) \
            --dart-define=${DART_DEFINES} \
            --export-options-plist=$CM_EXPORT_OPTIONS_PATH

      - name: Upload dSYM to Firebase
        script: |
          # クラッシュ解析用。もし不要ならこのステップを消すと1分節約できます
          find build/ios/archive -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true