workflows:
  release:
    name: Release (Tag -> Store)
    max_build_duration: 90
    instance_type: mac_mini_m1
    # --- 修正箇所：リスト形式ではなく辞書形式で記述 ---
    integrations:
      app_store_connect: "Your Integration Name" # CodemagicのWeb画面で設定した連携名
    # ---------------------------------------------
    environment:
      groups:
        - ios_credentials
        - android_credentials
        - notifications
      vars:
        FLUTTER_CHANNEL: "stable"
        APP_ENV: "prod"
        DART_DEFINES: "ENV=prod"
        ANDROID_FLAVOR: "prod"
      flutter: "3.24.0"
      xcode: "15.4"
      cocoapods: "1.14.3"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Set up GoogleService-Info.plist
        script: |
          echo "$GOOGLE_SERVICE_INFO_IOS" > ios/Runner/GoogleService-Info.plist
      - name: Prepare secrets (Android keystore)
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/keystores/release.keystore
      - name: Flutter deps
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
      - name: Tests
        script: |
          flutter test
      - name: Build Android App Bundle
        script: |
          flutter build appbundle \
            --release \
            --flavor ${ANDROID_FLAVOR} \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES}
      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.4.0 \
            --build-number=${BUILD_NUMBER} \
            --dart-define=${DART_DEFINES} \
            --export-options-plist=ios/exportOptions.plist
      - name: Upload dSYM to Firebase Crashlytics
        script: |
          find build/ios/archive -name "*.dSYM" | xcode-project upload-dsyms --app-id "$FIREBASE_APP_ID_IOS"
    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
      slack:
        channel: "#ci-notify"
        notify:
          success: true
          failure: true